[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
topic_counter = "8fwUnvsRypGyT17uHcp3gE6mCVT46FXqDhR1DDy4ZNee"

[programs.localnet]
topic_counter = "8fwUnvsRypGyT17uHcp3gE6mCVT46FXqDhR1DDy4ZNee"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 1000
shutdown_wait = 2000
upgradeable = false
